chain_width=80
comment_width=120
fn_call_width=120
format_code_in_doc_comments=true
hex_literal_case="Upper"
match_block_trailing_comma=true
max_width=120
tab_spaces=2
# use_small_heuristics="Default"
